# Generated by Django 5.0.12 on 2025-03-06 23:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "sections",
                    wagtail.fields.StreamField(
                        [("slider", 6)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                            3: (
                                "wagtail.blocks.StreamBlock",
                                [[("image", 1), ("video", 2)]],
                                {},
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("media", 3)]],
                                {},
                            ),
                            5: ("wagtail.blocks.StreamBlock", [[("slide", 4)]], {}),
                            6: ("wagtail.blocks.StructBlock", [[("slides", 5)]], {}),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
