# Generated by Django 5.0.12 on 2025-03-07 00:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="sections",
            field=wagtail.fields.StreamField(
                [("slider", 6), ("services", 9), ("news", 12), ("partners", 14)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                    3: (
                        "wagtail.blocks.StreamBlock",
                        [[("image", 1), ("video", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("media", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.StreamBlock", [[("slide", 4)]], {}),
                    6: ("wagtail.blocks.StructBlock", [[("slides", 5)]], {}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("description", 0), ("image", 1)]],
                        {},
                    ),
                    8: ("wagtail.blocks.StreamBlock", [[("service", 7)]], {}),
                    9: ("wagtail.blocks.StructBlock", [[("services", 8)]], {}),
                    10: ("wagtail.blocks.PageChooserBlock", (), {}),
                    11: ("wagtail.blocks.StreamBlock", [[("post", 10)]], {}),
                    12: ("wagtail.blocks.StructBlock", [[("news", 11)]], {}),
                    13: ("wagtail.blocks.StreamBlock", [[("partner", 1)]], {}),
                    14: ("wagtail.blocks.StructBlock", [[("partners", 13)]], {}),
                },
            ),
        ),
    ]
