# Generated by Django 5.0.12 on 2025-03-09 22:45

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_homepage_sections"),
    ]

    operations = [
        migrations.CreateModel(
            name="Navbar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Menu Name")),
                (
                    "items",
                    wagtail.fields.StreamField(
                        [("external", 6), ("internal", 7), ("document", 8)],
                        block_lookup={
                            0: ("wagtail.blocks.URLBlock", (), {"required": True}),
                            1: ("wagtail.blocks.StructBlock", [[("link", 0)]], {}),
                            2: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            3: ("wagtail.blocks.StructBlock", [[("link", 2)]], {}),
                            4: ("wagtail.blocks.StructBlock", [[]], {}),
                            5: (
                                "wagtail.blocks.StreamBlock",
                                [[("external", 1), ("internal", 3), ("document", 4)]],
                                {"required": False},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("link", 0), ("children", 5)]],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("link", 2), ("children", 5)]],
                                {},
                            ),
                            8: ("wagtail.blocks.StructBlock", [[("children", 5)]], {}),
                        },
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="homepage",
            name="sections",
            field=wagtail.fields.StreamField(
                [("slider", 3), ("services", 8), ("news", 11), ("partners", 13)],
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    1: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.StreamBlock",
                        [[("image", 0), ("video", 1)]],
                        {},
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("slides", 2)]], {}),
                    4: ("wagtail.blocks.CharBlock", (), {}),
                    5: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 4), ("description", 4), ("image", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.StreamBlock", [[("service", 6)]], {}),
                    8: ("wagtail.blocks.StructBlock", [[("services", 7)]], {}),
                    9: ("wagtail.blocks.PageChooserBlock", (), {}),
                    10: ("wagtail.blocks.StreamBlock", [[("post", 9)]], {}),
                    11: ("wagtail.blocks.StructBlock", [[("news", 10)]], {}),
                    12: ("wagtail.blocks.StreamBlock", [[("partner", 5)]], {}),
                    13: ("wagtail.blocks.StructBlock", [[("partners", 12)]], {}),
                },
            ),
        ),
    ]
