# Generated by Django 5.0.12 on 2025-03-09 22:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_navbar_alter_homepage_sections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navbar",
            name="items",
            field=wagtail.fields.StreamField(
                [("external", 8), ("internal", 9), ("document", 10)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("link", 1)]],
                        {},
                    ),
                    3: ("wagtail.blocks.PageChooserBlock", (), {"required": True}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("link", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": True},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("link", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.StreamBlock",
                        [[("external", 2), ("internal", 4), ("document", 6)]],
                        {"required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("link", 1), ("children", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("link", 3), ("children", 7)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("link", 5), ("children", 7)]],
                        {},
                    ),
                },
            ),
        ),
    ]
