# Generated by Django 5.0.12 on 2025-03-11 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_postrelatedposts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postrelatedposts",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="postrelatedposts",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="postrelatedposts",
            name="related_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.postpage",
            ),
        ),
    ]
